### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by vasnt** [InfrHQ/server#1]
https://www.infrhq.com/register it shows error
404: This page could not be found

found from READEME:
<img width="442" alt="image" src="https://github.com/InfrHQ/server/assets/117589240/98fe3d3d-4166-4eda-b739-e4aed5a0ffb4">

**Comment by synthpolis** [comment]
Thanks for pointing this out. We initially had the /register for alpha, but recently switched to the waitlist. I'll update the repo asap. In the meanwhile, you can join the waitlist at infrhq.com :)
